shanmao/urls.py
from django.conf.urls import url, include
from django.contrib import admin


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^',include('shanmao1.urls', namespace='sm'))
]

shanmao1/urls.py
from django.conf.urls import url

from shanmao1 import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^index/$', views.index, name='index1'),
    url(r'^login/$', views.login, name='login'),
    url(r'^register/$', views.register, name='register'),
    url(r'^nike/(\d+)/$', views.nike, name='nike'),
    url(r'^logout/$', views.logout, name='logout'),
    url(r'^balance/$', views.balance, name='balance'),


]

shanmao1/models.py
from django.db import models

# Create your models here.

# 商品
class Goods(models.Model):
    img = models.CharField(max_length=100)
    information = models.CharField(max_length=100)
    RMB = models.CharField(max_length=10)
    price = models.DecimalField(max_digits=6,decimal_places=2)
    original =models.DecimalField(max_digits=6,decimal_places=2)
    goodsid = models.CharField(max_length=8,default='')

# 用户
class User(models.Model):
    username = models.CharField(max_length=100)
    password = models.CharField(max_length=100)
    email = models.CharField(max_length=100)
    token = models.CharField(max_length=256,default='')

# 购物车
class Balance(models.Model):
    user = models.ForeignKey(User)
    goods = models.ForeignKey(Goods)
    number = models.IntegerField()
    isselect = models.BooleanField(default=True)

shanmao1/views.py
import hashlib
import random
import time

from django.http import HttpResponse, JsonResponse
from django.shortcuts import render, redirect

# Create your views here.
from shanmao1.models import Goods, User, Balance


def index(request):
    goodlist = Goods.objects.all()
    # username = request.COOKIES.get('username')
    token = request.session.get('token')
    # username = request.session.get('username')
    if token:
        users = User.objects.filter(token=token)
        user = users.first()
        # username = User.username

    else:
        user = None

    data = {
        'user': user,
        # 'username': username,
        'goodlist': goodlist

    }

    return render(request, 'index.html', context=data)


def generate_token():
    token = str(time.time()) + str(random.random())
    md5 = hashlib.md5()
    md5.update(token.encode('utf-8'))

    return md5.hexdigest()


def generate_password(password):
    md5 = hashlib.md5()
    md5.update(password.encode('utf-8'))
    return md5.hexdigest()


def register(request):
    if request.method == 'GET':
        return render(request, 'regist.html')
    elif request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        email = request.POST.get('email')

        user = User()
        user.email = email
        user.username = username
        user.password = generate_password(password)
        user.token = generate_token()
        user.save()

        response = redirect('sm:index')

        request.session['token'] = user.token

        # response.set_cookie('username',username)
        return response


def logout(request):
    response = redirect('sm:index')

    request.session.flush()
    return response


def login(request):
    if request.method == 'GET':
        return render(request, 'login.html')
    elif request.method == 'POST':
        username = request.POST.get('username')
        password = generate_password(request.POST.get('password'))

        users = User.objects.filter(username=username).filter(password=password)

        if users.count():
            response = redirect('sm:index')
            user = users.first()
            user.token = generate_token()
            user.save()
            request.session['token'] = user.token
            # response.set_cookie('token', user.token)
            return response
        else:

            return render(request, 'login.html', context={'err': '用户名或密码错误'})


def nike(request,id):
    token = request.session.get('token')
    users = User.objects.filter(token=token)
    user = users.first()
    if token:
        goods = Goods.objects.get(goodsid=int(id))
        goods.save()

        data = {
            'goods':goods,
            'id':id,
            'user': user,

        }
        return render(request, 'nike.html',context=data)
    else:
        return render(request,'login.html')




def addcart(request):
    token = request.session['token']
    goodsid = request.GET.get('goodsid')
    data = {}
    if token:
        user = User.objects.get(token=token)
        goods = Goods.objects.get(pk=goodsid)
        balances = Balance.objects.filter(user=user).filter(goods=goods)
        if balances.exists():
            pass
        else:
            balance = Balance()
            balance.user = user
            balance.goods = goods
            balance.number = 1
            balance.save()

        return  JsonResponse({'msg':'{},添加购物车成功'.format(goods.information), 'number': balance.number})
    else:
        data['msg'] = '请登录后操作!'
        data['status'] = -1
        return redirect('sm:login')


def balance(request):

    token = request.session.get('token')
    users = User.objects.filter(token=token)
    user = users.first()
    if token:


        data = {
            'user': user,

        }
        return render(request, 'balance.html',context=data)
    else:
        return render(request,'login.html')

templates/balance.html
{% load static %}
<!DOCTYPE html>
<html>

<head>
    <meta charset="UTF-8">
    <title></title>
    <link rel="stylesheet" href="{% static 'css/main.css' %}"/>
    <link rel="stylesheet" href="{% static 'css/balance.css' %}"/>
    <script type="text/javascript" src="{% static 'js/jquery-1.12.0.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/balance.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/jquery.cookie.js' %}"></script>
</head>

<body>
<div class="title">
    <span class="title_first">送货至：</span>
    <span class="destination">深圳<img class="arrow" src="{% static 'img/向下箭头.png' %}" alt=""/></span>
    <div class="login">
        {% if user %}
            {{ user.username }}
            <a href="{% url 'sm:logout' %}">退出</a>
        {% else %}
            <a href="{% url 'sm:login' %}">请登录</a>
            <a href="{% url 'sm:register' %}">注册</a>
        {% endif %}
    </div>
    <div class="title_nav" style="right: 50px;">
        <ul>
            <li>
                <a href="http://www.shanmao.net.cn/user.php?act=order_list">我的订单</a>
            </li>
            <li>
                <a href="http://www.shanmao.net.cn/history_list.php">我的浏览</a>
            </li>
            <li>
                <a href="http://www.shanmao.net.cn/user.php?act=collection_list">我的收藏</a>
            </li>
            <li>
                <a href="http://www.shanmao.net.cn/user.php?act=message_list">客户服务</a>
            </li>
            <li class="li_last">
                <a class="a_last" href="http://www.shanmao.net.cn/package.php">促销活动</a>
            </li>
        </ul>
    </div>
    <div id="li_last_nav">
        <ul>
            <li>
                <a href="http://www.shanmao.net.cn/auction.php">拍卖活动</a>
            </li>
            <li>
                <a href="http://www.shanmao.net.cn/activity.php">优惠礼包</a>
            </li>
            <li>
                <a href="http://www.shanmao.net.cn/wholesale.php">批发市场</a>
            </li>
            <li>
                <a href="http://www.shanmao.net.cn/package.php">超值礼包</a>
            </li>
        </ul>
    </div>
</div>

<div class="bal_header w1200">
    <div class="bal_logo">
        <a href="{% url 'sm:index' %}"><img src="{% static 'img/闪猫商城-您的一站式购物平台_09.png' %}" alt="闪猫商城"/></a>
    </div>
    <div class="bal_search">
        <form class="searchForm" name="serchForm" method="get">
            <div class="search_tabs">
                <i></i>
                <ul class="shop_serach">
                    <li><span style="margin-left: 15px;	font-size: 14px;">商品</span></li>
                    <li style="background: #EC5151;color: #fff;position: absolute;left: -1px;top: 36px;">
                        <span style="margin-left: 15px;	font-size: 14px;color: white;">店铺</span>
                    </li>
                </ul>
            </div>
            <input type="text" placeholder="周大福" name="keyword" class="keyword" style="color: #999;"/>
            <button class="search_button">
                <i></i>
            </button>
        </form>
    </div>
</div>

<div class="container">
    <div class="ecsc_shop w1200">
        <div class="ecsc_shop_title">
            <i></i>
            <h3 style="margin-left: 15px;float: left;font-size: 18px;color: #727171;font-weight: normal;">购物车（&nbsp;<em
                    class="check_num">0</em>&nbsp;）
            </h3>
        </div>
    </div>
    <div class="cart_warp w1200" style="padding-bottom: 40px;">
        <div class="ecsc_cart">
            <div class="cart_head">
                <div class="cart_checkbox column">
                    <input type="checkbox" class="check_all" style="vertical-align: middle;"/>
                    <label style="color: #000000;cursor: pointer;">全选</label>
                </div>
                <div class="column" style="width: 315px;">商品</div>
                <div class="column" style="width: 210px;">属性</div>
                <div class="column" style="width: 150px;">单价（元）</div>
                <div class="column" style="width: 140px;">数量</div>
                <div class="column" style="width: 120px;">小计（元）</div>
                <div class="column" style="width: 74px;">操作</div>
            </div>
            <div class="bal_cart_list">
                <div class="shop">
                    <input type="checkbox" class="shop_check" style="vertical-align: middle;"/>
                    <a style="cursor: pointer;">耐克旗舰店</a>
                </div>
                <div class="item_list">
                    <ul class="item_list_ul">
                        <img src="{{ goods.img }}" alt="">
                    </ul>
                </div>
                <div class="nogoods"
                     style="display: none;text-align: center;font-size: 20px;font-weight: bold;color: #EC5051;">
                    您还没有选择商品
                </div>
            </div>
            <div class="cart_price">
                <div style="float: left;">
                    <input type="checkbox" style="vertical-align: middle;margin-left: 30px;" class="select_all"/>
                    <label>全选</label>
                </div>
                <p class="bal_del">删除选择的商品</p>
                <p class="bal_move">移到我的收藏</p>
                <div class="cart_price_right">
                    <div class="btn_area" style="float: right;">
                        <input type="button" value="去结算"/>
                    </div>
                    <div class="price_num">
                        <span>总价（不含运费）：</span>
                        <span class="cart_goods_amount">
									<em>￥</em>
									￥0.00
								</span>
                    </div>
                    <div class="amount_sum">
                        已选择
                        <em class="cart_check_sum">0</em>
                        件商品
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
</body>

</html>

templates/login.html
{% load static %}
<!DOCTYPE html>
<html>

<head>
    <meta charset="UTF-8">
    <title>用户中心</title>
    <script type="text/javascript" src="{% static "js/jquery-1.12.0.js" %}"></script>
    <script type="text/javascript" src="{% static "js/jquery.cookie.js" %}"></script>
    <script type="text/javascript" src="{% static 'js/login.js' %}"></script>
    <link rel="stylesheet" href="{% static 'css/login.css' %}"/>
    <link rel="stylesheet" href="{% static 'css/main.css' %}"/>
    <style>
        .footer {
            border-top: 1px solid #ccc;
            padding-top: 0px;
        }

        .footer p {
            padding-top: 10px;
        }

        .footer a {
            font-size: 12px;
        }

        .footer a:hover {
            color: #EC5051;
        }
    </style>
</head>

<body>
<form action="{% url 'sm:login' %}" method="post" id="login-view">
    {% csrf_token %}

    <div class="login_title">
        <a href="{% url 'sm:index' %}">
            <img src="{% static 'img/login/logo_2015.png' %}" alt="logo"/>
        </a>
        <b></b>
    </div>
    <div class="login_contant">
        <i></i>
        <div id="login">
            <div class="login_information">
                <div class="mt">
                    <h1>欢迎登录</h1>
                    <a href="{% url 'sm:register' %}">免费注册</a>
                </div>
                <div class="mc">
                    <div class="msg_wrap">
                        <b></b>
                        <div class="msg_error">
                           用户名或密码错误



                        </div>
                    </div>
                    <div class="form">
                        <div class="id">
                            <div class="user_id">
                                <i></i>
                                <input type="text" name="username" placeholder="用户名/邮箱/手机" id="loginname"/>
                            </div>
                        </div>
                        <div class="login_item">
                            <div class="item_info">
                                <i></i>
                                <input type="password" name="password" id="psw" placeholder="密码"/>

                            </div>
                            {% if err %}
                                    <p style="color: red">{{ err }}</p>
                                {% endif %}
                        </div>
                        <div class="safe">
                            <input type="checkbox" id="remember"/>
                            <label>请保存我这次的登录信息。</label>
                        </div>
                        <div class="login_item">
								<span style="margin: 13px 0px 0px 30px;display: block;width: 76px;float: left;height: 14px;">
									<a href="#">忘记密码？</a>
								</span>
                            <div class="log">
                                <input type="submit" name="button" id="login_button" value="登&nbsp;&nbsp;录"/>
                            </div>
                        </div>
                    </div>
                    <div class="coagent" style="overflow: hidden;padding-top: 25px;">
                        <h6 style="font-weight: normal;color: #9fa0a0;float: left;width: 100%;">用第三方账号直接登录：</h6>
                        <ul>
                            <li>
                                <a href="#" style="background-position: -306px -307px;" class="qq"></a>
                            </li>
                            <li>
                                <a href="#" style="background-position: -369px -307px;" class="sina"></a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
</form>
<div class="footer" style="background: #fff;">
    <div class="copyright">
        <p class="footer_ecscinfo" style="line-height: 25px;">
            <a href="#">首页 </a>|
            <a href="#">隐私保护</a>|
            <a href="#">联系我们</a>|
            <a href="#">免责条款</a>|
            <a href="#">公司简介</a>|
            <a href="#">商家入驻</a>|
            <a href="#" style="border: 0px;">意见反馈</a>
        </p>
        <p>
            <a href="#">模板堂</a>|
            <a href="#">ECjia</a>|
            <a href="#">ECtouch</a>|
            <a href="#">电竞学院</a>|
            <a href="#">ecshop模板堂</a>|
            <a href="#">ECjia</a>|
            <a href="#">ECtouch</a>|
            <a href="#">大商创</a>
        </p>
        <p style="line-height: 18px;">
            <a href="#">Powered by<span style="color: #ec5051;padding-left: 5px">大商创1.0</span></a>
        </p>
        <p style="padding-top: 10px;">
            <a href="#"><img src="{% static 'img/images/闪猫商城-您的一站式购物平台_03.gif' %}" alt=""></a>
            <a href="#"><img src="{% static 'img/images/闪猫商城-您的一站式购物平台_05.gif' %}" alt=""></a>
            <a href="#"><img src="{% static 'img/images/闪猫商城-您的一站式购物平台_07.gif' %}" alt=""></a>
            <a href="#"><img src="{% static 'img/images/闪猫商城-您的一站式购物平台_09.gif' %}" alt=""></a>
            <a href="#"><img src="{% static 'img/images/闪猫商城-您的一站式购物平台_11.gif' %}" alt=""></a>
        </p>
    </div>
</div>
</div>
</body>

</html>

templates/regist.html
{% load static %}
<!DOCTYPE html>
<html>

	<head>
		<meta charset="UTF-8">
		<title>用户中心_注册新用户名</title>
		<script type="text/javascript" src="{% static 'js/jquery-1.12.0.js' %}"></script>
		<script type="text/javascript" src="{% static 'js/jquery.cookie.js' %}"></script>
		<script type="text/javascript" src="{% static 'js/register.js' %}"></script>
		<link rel="stylesheet" href="{% static 'css/login.css' %}" />
		<link rel="stylesheet" href="{% static 'css/main.css' %}" />
		<link rel="stylesheet" href="{% static 'css/regist.css' %}" />
		<style>
			.footer {
				border-top: 1px solid #ccc;
				padding-top: 0px;
			}
			
			.footer p {
				padding-top: 10px;
			}
			
			.footer a {
				font-size: 12px;
			}
			
			.footer a:hover {
				color: #EC5051;
			}
		</style>
	</head>

	<body>
		<div class="login_title">
			<a href="{% url 'sm:login' %}">
				<img src="{% static 'img/login/logo_2015.png' %}" alt="logo" />
			</a>
			<b></b>
			<p style="color: #696969;float: right;padding-top: 20px;">有账号
				<a href="{% url 'sm:login' %}" style="float: right;color: #3894ea;">在此登录</a>
			</p>
		</div>
		<div style="background: black;width: 100%;height: 1px;"></div>
		<div class="register" style="margin: auto;">
			<div style="float: left;padding: 64px 105px 64px 65px;">
				<a href="#"><img src="{% static 'img/regist/regist-banner.jpg' %}" alt="" /></a>
			</div>
			<div class="register_wrap">
				<div class="register_form" style="padding: 25px 0px 0px 35px; ">
					<div class="mt" style="height: 42px;overflow: hidden;">
						<ul>
							<li class="curr">邮箱注册</li>
							<li>手机注册</li>
						</ul>
					</div>
					<div class="mc">
						<div class="form_two">
							<form action="{% url 'sm:register' %}" method="post">
                                {% csrf_token %}
								<div class="register_item">
									<div class="register_item_info">
										<input type="text" id="username" name="username" placeholder="用户名" class="text" />
										<i class="i_user" style=""></i>
									</div>
									<div class="error" id="username_notice">
										<i></i>
										<label></label>
									</div>
								</div>
								<div class="register_item">
									<div class="register_item_info">
										<input type="text" id="email" name="email" placeholder="邮箱地址" class="text" />
										<i class="i_email"></i>
									</div>
									<div class="error" id="email_notice">
										<i></i>
										<label></label>
									</div>
								</div>
								<div class="register_item">
									<div class="register_item_info">
										<input type="password" id="password" name="password" placeholder="设置密码" class="text" maxlength="20" />
										<i class="i_pass"></i>
									</div>
									<div class="error" id="password_notice">
										<i class="i"></i>
										<label></label>
									</div>
								</div>
								<div class="register_item">
									<div class="register_item_info">
										<input type="password" id="confirm" name="confirm" placeholder="确认密码" class="text" maxlength="20" />
										<i class="i_confirm"></i>
									</div>
									<div class="error" id="confirm_notice">
										<i class="i"></i>
										<label></label>
									</div>
								</div>
								<div class="register_item">
									<div class="register_item_info">
										<input type="checkbox" id="check" name="check" checked="checked" style="float: left;margin-top: 14px;" />
										<label style="height: 40px;line-height: 40px;float: left;padding-left: 0;cursor: pointer;">阅读并同意《<a href="#" style="margin-top: 14px;color: #3a78bf;">服务协议</a>》</label>
									</div>
								</div>
								<div class="register_item">
									<div class="register_item_info">
										<input type="submit" id="regist_submit" name="submit" value="同意协议并注册" />
									</div>
								</div>
							</form>
						</div>
					</div>
				</div>
			</div>
		</div>

		<div class="footer" style="background: #fff;">
			<div class="copyright">
				<p class="footer_ecscinfo" style="line-height: 25px;">
					<a href="#">首页 </a>|
					<a href="#">隐私保护</a>|
					<a href="#">联系我们</a>|
					<a href="#">免责条款</a>|
					<a href="#">公司简介</a>|
					<a href="#">商家入驻</a>|
					<a href="#" style="border: 0px;">意见反馈</a>
				</p>
				<p>
					<a href="#">模板堂</a>|
					<a href="#">ECjia</a>|
					<a href="#">ECtouch</a>|
					<a href="#">电竞学院</a>|
					<a href="#">ecshop模板堂</a>|
					<a href="#">ECjia</a>|
					<a href="#">ECtouch</a>|
					<a href="#">大商创</a>
				</p>
				<p style="line-height: 18px;">
					<a href="#">Powered by<span style="color: #ec5051;padding-left: 5px">大商创1.0</span></a>
				</p>
				<p style="padding-top: 10px;">
						<a href="#"><img src="{% static 'img/images/闪猫商城-您的一站式购物平台_03.gif' %}" alt=""></a>
						<a href="#"><img src="{% static 'img/images/闪猫商城-您的一站式购物平台_05.gif' %}" alt=""></a>
						<a href="#"><img src="{% static 'img/images/闪猫商城-您的一站式购物平台_07.gif' %}" alt=""></a>
						<a href="#"><img src="{% static 'img/images/闪猫商城-您的一站式购物平台_09.gif' %}" alt=""></a>
						<a href="#"><img src="{% static 'img/images/闪猫商城-您的一站式购物平台_11.gif' %}" alt=""></a>

				</p>
			</div>
		</div>
		</div>
	</body>

</html>